### ISSUE TITLE
Install instructions for Linux

### ISSUE THREAD

**Issue by esagara** [overview/overview-local#1]
This line in the readme under Linux installation should be changed:

``` bash
sudo apt-get install docker
```

To:

``` bash
sudo apt-get install docker.io
```

**Comment by esagara** [comment]
Also I ran into an issue where the client and the server had different API versions. This fix [here](http://stackoverflow.com/questions/29727171/docker-compose-up-leads-to-client-and-server-dont-have-same-version-client) worked for me.

**Comment by jstray** [comment]
Fixed.
