### ISSUE TITLE
Documents with errors

### ISSUE THREAD

**Issue by agnewtj** [overview/overview-local#10]
Hi Guys,

I'm getting this error after uploading several docs:

Documents with errors
Failed with error “PDF is valid, but a bug in Overview means we can't load it”

Where would I go to find the specific error and diagnose?

Thanks,
Tom

**Comment by adamhooper** [comment]
@agnewtj Whew -- this bug slipped away from us.

To find the specific error, run `./tail-logs` or `./dump-logs`. We'd love to see what the logs say, so we can address the problem.

**Comment by adamhooper** [comment]
Absent more feedback, I'm closing this bug.
