### ISSUE TITLE
"Error in plugin code" in file-browser

### ISSUE THREAD

**Issue by adamhooper** [overview/overview-local#13]
@kmarhold wrote:

@adamhooper being a bit more careful this time, but Word Cloud and Entities seem to work now. Folders still doesn't, but the error is different - I get an "Error in Plugin Code" now, whereas before it was just stuck while processing. 

Here are the relevant logs:

```
overview-proxy                   | 2017-11-17T09:40:08.961013380Z Nov 17 09:40:08 4d9b601bc8dd local0.info haproxy[7]: 192.168.1.10:61450 [17/Nov/2017:09:40:08.957] https~ plugin_file_browser/overview-plugin-file-browser 0/0/1/1/2 304 273 - - ---- 5/5/0/1/0 0/0 "GET /show?server=http%3A%2F%2Foverview-web%3A9000&documentSetId=3&apiToken=2
overview-plugin-file-browser     | 2017-11-17T09:40:08.961089706Z ::ffff:172.18.0.8 - GET /show?server=http%3A%2F%2Foverview-web%3A9000&documentSetId=3&apiToken=2mpdzb27paqp7x8stxtpsk7lk HTTP/1.1 304 - - 0.536 ms
overview-proxy                   | 2017-11-17T09:40:09.101329564Z Nov 17 09:40:09 4d9b601bc8dd local0.info haproxy[7]: 192.168.1.10:61450 [17/Nov/2017:09:40:09.100] https~ plugin_file_browser/overview-plugin-file-browser 0/0/0/1/1 304 274 - - ---- 5/5/0/1/0 0/0 "GET /show.css HTTP/1.1"
overview-plugin-file-browser     | 2017-11-17T09:40:09.101274821Z ::ffff:172.18.0.8 - GET /show.css HTTP/1.1 304 - - 0.398 ms
overview-proxy                   | 2017-11-17T09:40:09.105325293Z Nov 17 09:40:09 4d9b601bc8dd local0.info haproxy[7]: 192.168.1.10:61460 [17/Nov/2017:09:40:09.102] https~ plugin_file_browser/overview-plugin-file-browser 0/0/0/2/2 304 276 - - ---- 6/6/0/1/0 0/0 "GET /main.js HTTP/1.1"
overview-plugin-file-browser     | 2017-11-17T09:40:09.105386047Z ::ffff:172.18.0.8 - GET /main.js HTTP/1.1 304 - - 0.447 ms
overview-web                     | 2017-11-17T09:40:09.347387059Z INFO application -  14ms GET /api/v1/document-sets/3/documents?stream=true&fields=title -> 200
overview-proxy                   | 2017-11-17T09:40:09.545850208Z Nov 17 09:40:09 4d9b601bc8dd local0.info haproxy[7]: 192.168.1.10:61450 [17/Nov/2017:09:40:09.324] https~ plugin_file_browser/overview-plugin-file-browser 0/0/0/220/220 304 156 - - ---- 6/6/0/1/0 0/0 "GET /folders?server=http%3A%2F%2Foverview-web%3A9000&documentSetId=3&api
overview-plugin-file-browser     | 2017-11-17T09:40:09.546187538Z ::ffff:172.18.0.8 - GET /folders?server=http%3A%2F%2Foverview-web%3A9000&documentSetId=3&apiToken=2mpdzb27paqp7x8stxtpsk7lk HTTP/1.1 304 - - 219.570 ms
```

**Comment by adamhooper** [comment]
@kmarhold Thanks for your help with other bugs. I'd be ever grateful if you could help with this one, too!

That "error in plugin code" is a message I just wrote yesterday. I expect that there's an explanation on the JavaScript console. Assuming you're using Google Chrome: could you please press Command+Option+J to open your JavaScript console, and then take a screenshot of every message in it?

**Comment by kmarhold** [comment]
Hi @adamhooper, sorry for the long silence. Here's the screenshot. I get the same message about HTTPS for the other plugins and it doesn't seem to affect them. 
<img width="516" alt="file-browser" src="https://user-images.githubusercontent.com/17476340/33986336-9282dcc2-e0bd-11e7-85be-08f601f5b8d7.png">

**Comment by adamhooper** [comment]
Thanks for the screenshot: it clearly identifies the problem.

The problem is that our plugin's client-side JavaScript is making an API request to the wrong URL. There are a number of solutions, and all of them seem icky to me. I'll have to ponder the way forward.

**Comment by adamhooper** [comment]
I'm happy to report: I finally have a fix ready. Just for file-browser; other plugins' errors I'll fix separately.

... however, since it's Friday evening, I won't deploy until Monday.

**Comment by adamhooper** [comment]
@kmarhold Thanks for your patience. Can you try a `./stop && ./update && ./start` and see whether this issue is fixed? You'll have to delete and recreate the File Browser plugin to make that happen.

**Comment by kmarhold** [comment]
Just tested and it works great. Thanks!

**Comment by adamhooper** [comment]
I've just deployed a fixed version of multi-search. Now it should save your searches, like it was always meant to.

**Comment by adamhooper** [comment]
At long last: I've updated all overview-local's plugins. They now correctly differentiate between `origin` (the parent iframe's server) and `server` (Overview's HTTP server, as seen from the child iframe's server).

**Comment by kmarhold** [comment]
Thanks @adamhooper, everything's working as expected now. Let me know if I can help testing/debugging any further!
