### ISSUE TITLE
Document tab doesn't render PDF document in the view

### ISSUE THREAD

**Issue by jayminkapish** [overview/overview-local#15]
We're spinning up OverviewDocs in our GKE cluster.

We're seeing a strange error every time we try to view a document in the PDF viewer(?) in the `overview-web` UI. I'm not very familiar with all the features of Overview yet so I could be doing something I'm not suppose to. 

From two views or tabs in the UI, Document and Text, Text does show parsed text from the PDF but clicking on Document tab logs the following and doesn't render document in the view:

```
WARN c.a.u.EC2MetadataUtils - Unable to retrieve the requested metadata.
INFO application -   6ms GET /documents/115964116993.pdf -> 200
```

Since this error is recorded as Warn and response from /documents/115964116993.pdf is 200, there is no enough information in logs. Though, /documents/115964116993.txt does return parsed text from the document. That leads me to believe overview-web backend side of things wherever /documents/115964116993.pdf routes to, requires some AWS resource metadata, where resource could be an EC2 instance or something else, assuming we're operating in AWS? The only AWS dependency we have on our side is S3 and the IAM role + bucket policy doesn't allow any other resource access to the set keys than S3 bucket where documents are uploaded to.

Error leads me to the following file/line in aws-sdk-java repo:
https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java#L386

I am still walking through the code from js/coffeescript to aws-sdk-java client and may update this issue with more findings.

**Comment by adamhooper** [comment]
Hi @jayminkapish,

Let's move this discussion over to https://github.com/overview/overview-server/issues. I'll open an issue there, copy your text, and reply there.
