### ISSUE TITLE
Install instructions doesn't work

### ISSUE THREAD

**Issue by srabremix** [overview/overview-local#16]
Fresh install of Win 10 Pro 64bit. I get this:

-----
$ curl https://raw.githubusercontent.com/overview/overview-local/master/install-from-scratch.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1368  100  1368    0     0    342      0  0:00:04  0:00:04 --:--:--   435
Changing to home directory...
Removing any previous overview-local repository...
Downloading overview-local repository...
Cloning into 'overview-local'...
remote: Counting objects: 540, done.
Rreceiving objects:  73% (395/540), 84.01 emote: Total 540 (delta 0), reused 0 (delta 0), pack-reused 540
/s
Receiving objects: 100% (540/540), 99.74 KiB | 59.00 KiB/s, done.
Resolving deltas: 100% (332/332), done.
Checking connectivity... done.
Launching...
grep: overview-local/config/overview.env: No such file or directory
Updating overview-local repository...
grep: /c/Users/Overview/overview-local/config/overview.env: No such file or directory
Launching database...
overviewlocal_overview-database_1 is up-to-date
Applying latest schema...
C:\Program Files\Docker Toolbox\docker.exe: open /c/Users/Overview/overview-local/config/overview.defaults.env: The system cannot find the path specified.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
Command failed with error 125

Here are some commands for future reference:

overview-local/start: start Overview.
overview-local/stop: stop Overview.
overview-local/update: download a newer version of Overview.
overview-local/tail-logs: show log messages as they appear (Ctrl+C to stop).
overview-local/dump-logs: dump past log messages.
-----

Yes, the files are there:
Overview@DESKTOP-4MINGW64 /c/users/Overview/overview-local/config (master)
$ ls
overview.defaults.env  overview.env  overview.yml  overview-ssl.yml

**Comment by adamhooper** [comment]
I'm going to try to debug this without actually having Windows 10. Could you please copy/paste this command into your shell and report the output:

`ls -l /c/Users/Overview/overview-local/config/overview.defaults.env`

My thinking: it looks like you're in `/c/users/` and the script is looking in `/c/Users/`. Maybe MingW64 is confused?

More importantly, perhaps _docker_ is case-sensitive. Please copy/paste this stuff into the shell and describe how it goes:

```sh
docker pull alpine:3.7
docker run --rm --env-file /c/Users/Overview/overview-local/config/overview.defaults.env alpine:3.7 sh -c 'echo hello, world'
```

**Comment by srabremix** [comment]
Ok. I'll give it a try later. For now, I "solved" it by installing Ubuntu instead.

**Comment by adamhooper** [comment]
dup of #5

**Comment by adamhooper** [comment]
@srabremix The good news: I finally have time to look into this. The bad news: it works for me.

Could you please tell me the output of:

`git --version` (mine is `git version 2.16.1.windows.4`)
`bash --version` (mine is `GNU bash, version 4.4.12(2)-release (x86_64-pc-msys)`)

And please click Start -> type "System Information" and open that. Under 'System summary", what's your "OS Name" and "Version"? (Mine is "Microsoft Windows 10 Enterprise Evaluation" and "10.0.16299 Build 16299")

**Comment by adamhooper** [comment]
Absent more feedback, I'm closing this issue.
