### ISSUE TITLE
email exceptions when using custom smtp

### ISSUE THREAD

**Issue by bobweston** [overview/overview-local#22]
This version of Overview is running inside our Firewall. The company has set up an internal smtp server for this sort of thing. But I'm getting errors reporting that it cannot access the smtp server.

The other bit if information here is that this smtp server is inside our company firewall. It doesn't require username or password. I've tried setting those values to an empty string, null and even not setting them at all. But it still returns "play.api.UnexpectedException: Unexpected exception[EmailException: Sending the email to the following server failed : "smtp-ctc.xx.org":25]"

This server is currently working with other applications. So I'm reasonably confident that it isn't the server.

The only other thing I can think of is that perhaps this is some sort of docker networking issue? 

Any help you can provide would be really appreciated.

The full error logs are below:

overview-web_1                   | 2020-01-31T14:57:05.806123274Z ERROR application -
overview-web_1                   | 2020-01-31T14:57:05.806153616Z
overview-web_1                   | 2020-01-31T14:57:05.806159128Z ! @7ek5m3404 - Internal server error, for (POST) [/register] ->
overview-web_1                   | 2020-01-31T14:57:05.806172753Z
overview-web_1                   | 2020-01-31T14:57:05.806178496Z play.api.UnexpectedException: Unexpected exception[EmailException: Sending the email to the following server failed : "smtp-ctc.xx.org":25]
overview-web_1                   | 2020-01-31T14:57:05.806183245Z 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:247)
overview-web_1                   | 2020-01-31T14:57:05.806209198Z 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:178)
overview-web_1                   | 2020-01-31T14:57:05.806217446Z 	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:382)
overview-web_1                   | 2020-01-31T14:57:05.806222214Z 	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:380)
overview-web_1                   | 2020-01-31T14:57:05.806226035Z 	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
overview-web_1                   | 2020-01-31T14:57:05.806229904Z 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
overview-web_1                   | 2020-01-31T14:57:05.806233488Z 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
overview-web_1                   | 2020-01-31T14:57:05.806237446Z 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
overview-web_1                   | 2020-01-31T14:57:05.806241206Z 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
overview-web_1                   | 2020-01-31T14:57:05.806244789Z 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
overview-web_1                   | 2020-01-31T14:57:05.806248335Z 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
overview-web_1                   | 2020-01-31T14:57:05.806252218Z 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
overview-web_1                   | 2020-01-31T14:57:05.806256177Z 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
overview-web_1                   | 2020-01-31T14:57:05.806274924Z 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
overview-web_1                   | 2020-01-31T14:57:05.806278777Z 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
overview-web_1                   | 2020-01-31T14:57:05.806281953Z 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
overview-web_1                   | 2020-01-31T14:57:05.806285112Z 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
overview-web_1                   | 2020-01-31T14:57:05.806288245Z 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
overview-web_1                   | 2020-01-31T14:57:05.806291437Z Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : "smtp-ctc.xx.org":25
overview-web_1                   | 2020-01-31T14:57:05.806294812Z 	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
overview-web_1                   | 2020-01-31T14:57:05.806297948Z 	at org.apache.commons.mail.Email.send(Email.java:1496)
overview-web_1                   | 2020-01-31T14:57:05.806301266Z 	at play.api.libs.mailer.SMTPMailer$$anon$1.send(SMTPMailer.scala:14)
overview-web_1                   | 2020-01-31T14:57:05.806305322Z 	at play.api.libs.mailer.CommonsMailer.send(CommonsMailer.scala:21)
overview-web_1                   | 2020-01-31T14:57:05.806308596Z 	at play.api.libs.mailer.SMTPMailer.send(SMTPMailer.scala:24)
overview-web_1                   | 2020-01-31T14:57:05.806311738Z 	at play.api.libs.mailer.SMTPDynamicMailer.send(SMTPDynamicMailer.scala:8)
overview-web_1                   | 2020-01-31T14:57:05.806314966Z 	at mailers.Mailer.send(Mailer.scala:24)
overview-web_1                   | 2020-01-31T14:57:05.806318008Z 	at controllers.UserController$BlockingDatabaseBackendStuff.mailExistingUser(UserController.scala:139)
overview-web_1                   | 2020-01-31T14:57:05.806321191Z 	at controllers.UserController.handleExistingUser(UserController.scala:82)
overview-web_1                   | 2020-01-31T14:57:05.806324315Z 	at controllers.UserController.$anonfun$create$3(UserController.scala:48)
overview-web_1                   | 2020-01-31T14:57:05.806327453Z 	at play.api.data.Form.fold(Form.scala:146)
overview-web_1                   | 2020-01-31T14:57:05.806330552Z 	at controllers.UserController.$anonfun$create$1(UserController.scala:46)
overview-web_1                   | 2020-01-31T14:57:05.806333718Z 	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
overview-web_1                   | 2020-01-31T14:57:05.806336816Z 	at play.api.mvc.MessagesActionBuilderImpl.invokeBlock(MessagesRequest.scala:70)
overview-web_1                   | 2020-01-31T14:57:05.806339975Z 	at play.api.mvc.MessagesActionBuilderImpl.invokeBlock(MessagesRequest.scala:66)
overview-web_1                   | 2020-01-31T14:57:05.806343133Z 	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:419)
overview-web_1                   | 2020-01-31T14:57:05.806346255Z 	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
overview-web_1                   | 2020-01-31T14:57:05.806349491Z 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
overview-web_1                   | 2020-01-31T14:57:05.806352711Z 	... 13 common frames omitted
overview-web_1                   | 2020-01-31T14:57:05.806355739Z Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: "smtp-ctc.xx.org", 25; timeout 60000
overview-web_1                   | 2020-01-31T14:57:05.806359069Z 	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2118)
overview-web_1                   | 2020-01-31T14:57:05.806362194Z 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
overview-web_1                   | 2020-01-31T14:57:05.806368532Z 	at javax.mail.Service.connect(Service.java:388)
overview-web_1                   | 2020-01-31T14:57:05.806407385Z 	at javax.mail.Service.connect(Service.java:246)
overview-web_1                   | 2020-01-31T14:57:05.806410859Z 	at javax.mail.Service.connect(Service.java:195)
overview-web_1                   | 2020-01-31T14:57:05.806413533Z 	at javax.mail.Transport.send0(Transport.java:254)
overview-web_1                   | 2020-01-31T14:57:05.806417103Z 	at javax.mail.Transport.send(Transport.java:124)
overview-web_1                   | 2020-01-31T14:57:05.806419808Z 	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)
overview-web_1                   | 2020-01-31T14:57:05.806422522Z 	... 30 common frames omitted
overview-web_1                   | 2020-01-31T14:57:05.806425132Z Caused by: java.net.UnknownHostException: "smtp-ctc.xx.org"
overview-web_1                   | 2020-01-31T14:57:05.806427937Z 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
overview-web_1                   | 2020-01-31T14:57:05.806430694Z 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
overview-web_1                   | 2020-01-31T14:57:05.806433363Z 	at java.net.Socket.connect(Socket.java:589)
overview-web_1                   | 2020-01-31T14:57:05.806436018Z 	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:329)
overview-web_1                   | 2020-01-31T14:57:05.806438701Z 	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
overview-web_1                   | 2020-01-31T14:57:05.806459047Z 	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2084)
overview-web_1                   | 2020-01-31T14:57:05.806462301Z 	... 37 common frames omitted
overview-proxy_1                 | 2020-01-31T14:57:05.809044714Z Jan 31 14:57:05 8ad697697229 local0.info haproxy[9]: 172.18.0.1:34346 [31/Jan/2020:14:57:05.351] www web/overview-web 0/0/0/457/457 500 1309 - - ---- 1/1/0/1/0 0/0 "POST /register HTTP/1.1"

**Comment by adamhooper** [comment]
Thank you for the issue report -- and the log.

The interesting line: `Caused by: java.net.UnknownHostException: "smtp-ctc.xx.org"` That suggests a DNS issue.

When you type `host smtp-ctc.xx.org` (or `nslookup smtp-ctc.xx.org`) from the machine that runs `overview-local`, does it succeed? Also, what is the operating system of the machine that runs `overview-local`?

**Comment by bobweston** [comment]
hey Adam,

the problem exists between my keyboard and chair. I had set SMTP_HOST="smtp-ctc.xx.org"

It should have been SMTP_HOST=smtp-ctc.ap.org

**Comment by bobweston** [comment]
Adam,

The problem existed between my keyboard and chair.

I had set the value like this: SMTP_HOST="smtp-ctc.xx.org"

It should have been SMTP_HOST=smtp-ctc.xx.org
