### ISSUE TITLE
feature request: way to override documentcloud url in overview_local

### ISSUE THREAD

**Issue by bobweston** [overview/overview-local#23]
Is there a way using overview-local to change (ideally add) a link to our internal (inside the firewall) version of documentcloud?

On our older version (based on overview_server) we modified the "overview.documentcloud_url" variable in a couple of places to point to a different url. 

Ideally, we could offer both links (so it would be possible to let users pull from either source). But being able to point to our internal version over the public one would be better than nothing. I didn't see this an option in overview.env.

**Comment by adamhooper** [comment]
You can set `DOCUMENTCLOUD_URL` in your `overview.env`. While you're at it, you may want to review other options documented at https://github.com/overview/overview-server/wiki/Configuration

We'd love to support multiple DocumentCloud versions. But it wouldn't be free. Please feel welcome to contact us at info@overviewdocs.com if you'd like to pursue that avenue.

**Comment by bobweston** [comment]
thanks, Adam!
