### ISSUE TITLE
uninstalling documentation typo?

### ISSUE THREAD

**Issue by bobweston** [overview/overview-local#24]
I'm running through the uninstall process and I think I've spotted a couple of typos.

Should these be changed?:

```
docker rm -v overview-blob-storage     # delete PDFs and uploaded files
docker rm -v overview-database-data    # delete database
docker rm -v overview-searchindex-data # delete search index
```

After shutting down the app (with ~/overview-local/stop), those containers should no longer exist. So trying to remove them results in "no such container."

```
CTCIDGMBRWES:~ robertweston $ docker rm -v overview-blob-storage
Error: No such container: overview-blob-storage
CTCIDGMBRWES:~ robertweston $ docker rm -v overview-database-data
Error: No such container: overview-database-data
CTCIDGMBRWES:~ robertweston $ docker rm -v overview-searchindex-data
Error: No such container: overview-searchindex-data
```
I checked and, as expected, the volumes still exist (which means a future install of the app will still contain the old data. Maybe that's intentional?)

I think a complete uninstall should include running:

```
docker volume rm overviewlocal_overview-database-data
docker volume rm overviewlocal_overview-searchindex-data
docker volume rm overviewlocal_overview-blob-storage
docker volume rm overviewlocal_overview-acme
```

**Comment by adamhooper** [comment]
Thank you for the report! You are indeed correct.
