### ISSUE TITLE
Overview on Chromebook

### ISSUE THREAD

**Issue by Sev19** [overview/overview-local#26]
Would it be possible to run Overview locally, on a Chromebook, without running a Linux OS w/Crostini or w/Crouton?  

Newer Chromebooks can run apps natively, using GooglePlay or FDroid.

Thank you. Overview is a must-have resource, for me. I love it.

**Comment by adamhooper** [comment]
This won't be possible. For cross-platform support, we use Docker. Docker works on Linux, Mac and Windows ... but not Chromebook.

I'm glad you use Overview! Too bad this is a no.
