### ISSUE TITLE
overview not running on port mentioned in terminal

### ISSUE THREAD

**Issue by micahstubbs** [overview/overview-local#6]
when I run `~/overview-local/start`

I see `Overview is running: browse to http://192.168.99.100:9000 to use it`

when I navigate to http://192.168.99.100:9000

 I see this Chrome error page:

<img width="620" alt="screen shot 2016-10-01 at 8 54 08 pm" src="https://cloud.githubusercontent.com/assets/2119400/19018520/3ff1306a-8819-11e6-8a4a-df7d9a265aea.png">

on the other hand, the address [http://localhost:9000/](http://localhost:9000/) does work. updating the terminal text to that address or some address that reliably resolves to it would improve dev ergonomics 😄 

what I see when I visit [http://localhost:9000/](http://localhost:9000/)

<img width="1107" alt="screen shot 2016-10-01 at 8 56 02 pm" src="https://cloud.githubusercontent.com/assets/2119400/19018525/84afa93e-8819-11e6-9998-66c8e07810f2.png">

**Comment by jstray** [comment]
Hi. What operating system is this?

**Comment by micahstubbs** [comment]
hi @jstray, this was running on `Mac OS El Capitan 10.11.6`

**Comment by jstray** [comment]
Still having the same problem?

**Comment by micahstubbs** [comment]
@jstray yes, still see the issue

**Comment by jstray** [comment]
Hmm. Can you do an `ifconfig` at the terminal, and  a `docker-machine ip` and paste in the output?

**Comment by adamhooper** [comment]
@micahstubbs Could you please try now? We've rejiggered networking to follow the Docker recommended practice: we'll always point you at `http://localhost:9000` now.

(The reason we didn't suggest `http://localhost:9000` earlier is because it broke plugins. We've fixed our issues with plugins.)

**Comment by adamhooper** [comment]
Missing confirmation from the user; but we knew and saw the problem and fixed it for ourselves, so let's assume it works for everybody?

I've updated `README.md` to point to the correct URL, `http://localhost:9000`.
