### ISSUE TITLE
Attempt to follow Windows directions

### ISSUE THREAD

**Issue by unicorncurves** [overview/overview-local#8]
After following the directions for Windows install I keep getting the error:

ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

To which I follow the directions listed for that issue. Still can't seem to get the program to run and continually running into the same error. I know this is probably user error, I just have no idea what I am doing wrong!

**Comment by jstray** [comment]
Do the directions in https://github.com/overview/overview-local#starting-overview solve this problem?
